### ISSUE TITLE
Models files license

### ISSUE THREAD

**Issue by darealshinji** [WL-Amigo/waifu2x-converter-cpp#7]
What are the license conditions of the models files?

**Comment by WL-Amigo** [comment]
Model files under this repository are converted from original waifu2x's model files using appendix/export_model_nocuda.lua .
Therefore, these files licensed with MIT License that is original waifu2x's license.

Sorry for my forgetting to write conditions for these files to LICENSE text.
I will add conditions to LICENSE at a later date.

(If you are considering to use models under this repository, I recommend to use original waifu2x's latest models. Because models under this repository are outdated.
Original models are also available with JSON format.)

**Comment by darealshinji** [comment]
Thanks for clearing this up.
